project_name: humanlog
release:
  github:
    owner: casualjim
    name: humanlog
  name_template: '{{.Tag}}'
brews:
  - name: humanlog
    github:
      owner: casualjim
      name: homebrew-humanlog-cj
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    commit_author:
      name: casualjim
      email: ivan@flanders.co.nz
    install: bin.install "humanlog"
scoop:
  name: humanlog
  commit_author:
    name: casualjim
    email: ivan@flanders.co.nz
  url_template: https://github.com/casualjim/humanlog/releases/download/{{ .Tag }}/{{.ArtifactName }}
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  targets:
  - linux_amd64
  - darwin_amd64
  main: ./cmd/humanlog/main.go
  ldflags: 
  - -s -w -X main.version={{.Version}}
  binary: humanlog
  env:
  - CGO_ENABLED=0
  lang: go
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      "386": i386
      amd64: x86_64
      darwin: Darwin
      linux: Linux
      windows: Windows
    format: binary
    files:
    - licence*
    - LICENCE*
    - license*
    - LICENSE*
    - readme*
    - README*
    - changelog*
    - CHANGELOG*
nfpms:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcrafts:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: dist
signs:
- cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  download: https://github.com
